help:		## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/://' -e 's/##//'
frontend:
	@echo Installing Frontend
catalogue:
	@echo Installing Catalogue
cart:
	@echo Installing Cart
user:
	@echo Installing User
shipping:
	@echo Installing Shipping
payment:
	@echo Installing Payment
mangodb:
	@echo Installing MangoDB
redis:
	@echo Installing Redis
mysql:
	@echo Installing MySQL
rabbitmq:
	@echo Installing Rabbitmq